# Generated by Django 2.2.3 on 2019-07-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='branch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
