# Generated by Django 2.2.3 on 2019-07-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190725_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
